Data Description: Given a Bank customer, can we build a classifier that can determine whether they will leave or not using Neural networks?


The dataset contains 10,000 sample points with 14 distinct features such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance etc. Know your data: https://www.kaggle.com/barelydedicated/bank-
customer-churn-modeling.

 

Context:
Businesses like banks which provide service have to worry about problem of 'Churn' i.e. customers leaving and joining another service provider. It is important to understand which aspects of the service influence a
customer's decision in this regard. Management can concentrate efforts on improvement of service, keeping in mind these priorities.

Steps and Milestones (100%):


 Setup Environment and Load Necessary Packages (5%)

 Data Preparation (40%)
o Loading Data (5%)
o Cleaning Data (10%)
o Data Representation & Feature Engineering (If Any) (15%)
o Creating Train and Validation Set (10%)

 Model Creation (30%)
o Write & Configure Model (10%)
o Compile Model (10%)
o Build Model & Checking Summary (10%)

 Training and Evaluation (25%)
o Run Multiple Experiments (10%)
o Reason & Visualize Model Performance (5%)
o Evaluate Model on Test Set (10%)

Learning Outcomes:
o Neural Networks for Predictive Analytics
o Fine-tuning Model
o Data Preparation
o Feature Engineering
o Visualization

 

The points distribution for this case is as follows:

Read the data set
Drop the columns which are unique for all users like IDs (2.5 points)
Distinguish the feature and target set (2.5 points)
Divide the data set into training and test sets ( 2.5 points)
Normalize the train and test data (5 points)
Initialize & build the model (10 points)
Predict the results using 0.5 as a threshold (5 points)
Print the Accuracy score and confusion matrix (2.5 points)
Case file: bank.csv

In [10]:
import numpy as np
import pandas as pd
Bank_df=pd.read_csv('bank.csv')

In [11]:
Bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [13]:
Bank_df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [14]:
drop_list=["CustomerId","Exited","Surname"]
New_Bank_df=Bank_df.drop(drop_list,axis=1)

In [15]:
New_Bank_df.head()
Bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [16]:
New_Bank_df.groupby(["Geography"]).count()

RowNumber  CreditScore  Gender   Age  Tenure  Balance  \
Geography                                                          
France          5014         5014    5014  5014    5014     5014   
Germany         2509         2509    2509  2509    2509     2509   
Spain           2477         2477    2477  2477    2477     2477   

           NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
Geography                                                             
France              5014       5014            5014             5014  
Germany             2509       2509            2509             2509  
Spain               2477       2477            2477             2477

In [17]:
#Encoding all the object data types.
New_Bank_obj = New_Bank_df.select_dtypes(include=['object']).copy()
cleanup_nums = {"Gender": {"Female": 0, "Male": 1 },"Geography":{"France": 0, "Germany": 1,"Spain":2 }}
X_df=New_Bank_df.replace(cleanup_nums, inplace=False)# Replacing the categorical Target variable with the binary encoded values.
X_df.head()

RowNumber  CreditScore  Geography  Gender  Age  Tenure    Balance  \
0          1          619          0       0   42       2       0.00   
1          2          608          2       0   41       1   83807.86   
2          3          502          0       0   42       8  159660.80   
3          4          699          0       0   39       1       0.00   
4          5          850          2       0   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0              1          1               1        101348.88  
1              1          0               1        112542.58  
2              3          1               0        113931.57  
3              2          0               0         93826.63  
4              1          1               1         79084.10

In [19]:
X=X_df.values
#print("The following are the features\n",col_names)
Y_df=Bank_df.iloc[:,13]
Y=Y_df.values
Y_df.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [20]:
print(X_df.shape,Y_df.shape)
print("Target Set is \n",Y_df.head())

(10000, 11) (10000,)
Target Set is 
 0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=7)

In [22]:
print(X_train)

[[4.8820000e+03 5.7900000e+02 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 2.6149250e+04]
 [9.0000000e+01 6.3500000e+02 1.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.5679136e+05]
 [8.4600000e+02 5.0500000e+02 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3518011e+05]
 ...
 [5.7000000e+03 6.8400000e+02 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 8.7219410e+04]
 [5.3800000e+02 6.8600000e+02 2.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.2756980e+05]
 [9.4130000e+03 7.2500000e+02 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3372057e+05]]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
X_train

array([[-0.03769042, -0.7457425 , -0.90549962, ...,  0.64738759,
        -1.03667198, -1.28306535],
       [-1.69335299, -0.16469943,  0.30118964, ...,  0.64738759,
         0.96462528,  0.98168193],
       [-1.43215079, -1.51354942, -0.90549962, ..., -1.54466971,
        -1.03667198,  0.60703995],
       ...,
       [ 0.24493312,  0.34371326, -0.90549962, ...,  0.64738759,
         0.96462528, -0.22438313],
       [-1.5385665 ,  0.3644648 ,  1.5078789 , ...,  0.64738759,
        -1.03667198,  0.47511136],
       [ 1.52779521,  0.7691198 , -0.90549962, ..., -1.54466971,
        -1.03667198,  0.58173808]])

In [25]:
X_test

array([[-1.04103852e+00,  6.86113649e-01,  1.50787890e+00, ...,
        -1.54466971e+00, -1.03667198e+00,  1.29335321e+00],
       [-3.83541467e-01,  2.71082880e-01, -9.05499619e-01, ...,
         6.47387589e-01,  9.64625280e-01,  9.26435059e-01],
       [-1.70613669e+00,  1.42279326e+00, -9.05499619e-01, ...,
        -1.54466971e+00, -1.03667198e+00,  2.91500424e-01],
       ...,
       [-8.97653717e-01, -1.94386578e-02,  1.50787890e+00, ...,
         6.47387589e-01,  9.64625280e-01,  8.70720991e-01],
       [-4.33985276e-01,  1.50579942e+00,  3.01189639e-01, ...,
         6.47387589e-01,  9.64625280e-01, -9.31746731e-01],
       [ 8.55786921e-01,  1.31288066e-03,  3.01189639e-01, ...,
         6.47387589e-01,  9.64625280e-01, -4.21692933e-01]])

In [26]:
import tensorflow as tf #Initialize & build the model
print(tf.__version__)

2.0.0


In [27]:
tf.random.set_seed(42)

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [29]:
#Initialize Sequential model
model = Sequential()
#Add input layer
model.add(Dense(11, input_dim = 11, kernel_initializer = 'uniform', activation='relu', name='input_layer'))

In [30]:
#Add hidden layer
model.add(Dense(10, kernel_initializer = 'uniform', activation = 'relu', name='hidden_layer_1'))
#Add Output layer
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid', name='output_layer'))

In [31]:
#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [32]:
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 11)                132       
_________________________________________________________________
hidden_layer_1 (Dense)       (None, 10)                120       
_________________________________________________________________
output_layer (Dense)         (None, 1)                 11        
Total params: 263
Trainable params: 263
Non-trainable params: 0
_________________________________________________________________
None


In [33]:
# Fitting the ANN
model.fit(X_train,Y_train, epochs=100,validation_data=(X_test,Y_test))

Train on 7500 samples, validate on 2500 samples
Epoch 1/100
7500/7500 [==============================] - 3s 391us/sample - loss: 0.5333 - accuracy: 0.7964 - val_loss: 0.4404 - val_accuracy: 0.7960
Epoch 2/100
7500/7500 [==============================] - 1s 92us/sample - loss: 0.4352 - accuracy: 0.7964 - val_loss: 0.4351 - val_accuracy: 0.7960
Epoch 3/100
7500/7500 [==============================] - 1s 83us/sample - loss: 0.4309 - accuracy: 0.7964 - val_loss: 0.4328 - val_accuracy: 0.7960
Epoch 4/100
7500/7500 [==============================] - 1s 82us/sample - loss: 0.4274 - accuracy: 0.7964 - val_loss: 0.4298 - val_accuracy: 0.7960
Epoch 5/100
7500/7500 [==============================] - 1s 92us/sample - loss: 0.4240 - accuracy: 0.7964 - val_loss: 0.4282 - val_accuracy: 0.7960
Epoch 6/100
7500/7500 [==============================] - 1s 76us/sample - loss: 0.4217 - accuracy: 0.8109 - val_loss: 0.4259 - val_accuracy: 0.8208
Epoch 7/100
7500/7500 [==============================] - 1s 71u

Epoch 56/100
7500/7500 [==============================] - 1s 78us/sample - loss: 0.3973 - accuracy: 0.8377 - val_loss: 0.4092 - val_accuracy: 0.8292
Epoch 57/100
7500/7500 [==============================] - 1s 85us/sample - loss: 0.3978 - accuracy: 0.8377 - val_loss: 0.4085 - val_accuracy: 0.8276
Epoch 58/100
7500/7500 [==============================] - 1s 75us/sample - loss: 0.3972 - accuracy: 0.8397 - val_loss: 0.4071 - val_accuracy: 0.8288
Epoch 59/100
7500/7500 [==============================] - 1s 85us/sample - loss: 0.3971 - accuracy: 0.8400 - val_loss: 0.4086 - val_accuracy: 0.8272
Epoch 60/100
7500/7500 [==============================] - 1s 77us/sample - loss: 0.3971 - accuracy: 0.8389 - val_loss: 0.4092 - val_accuracy: 0.8272
Epoch 61/100
7500/7500 [==============================] - 1s 71us/sample - loss: 0.3965 - accuracy: 0.8385 - val_loss: 0.4073 - val_accuracy: 0.8280
Epoch 62/100
7500/7500 [==============================] - 1s 79us/sample - loss: 0.3970 - accuracy: 0.8387

In [34]:
Y_pred = model.predict(X_test)

In [35]:
Y_pred = (Y_pred > 0.5).astype(np.int)#Predict the results using 0.5 as a threshold
Bank_test_predict=pd.DataFrame(X_test,columns=X_df.columns)
Bank_test_predict["Predicted"]=Y_pred
Bank_test_predict["Actual"]=Bank_df["Exited"]
Bank_test_predict.head()

RowNumber  CreditScore  Geography    Gender       Age    Tenure   Balance  \
0  -1.041039     0.686114   1.507879  0.916783 -0.370618 -1.386059 -1.234912   
1  -0.383541     0.271083  -0.905500 -1.090771  3.131735  1.025877 -1.234912   
2  -1.706137     1.422793  -0.905500 -1.090771 -0.559935 -0.007810 -1.234912   
3  -0.842718    -1.181525  -0.905500 -1.090771  1.333229 -0.696935 -1.234912   
4  -0.948098     0.686114   1.507879 -1.090771  0.008014  0.336752 -1.234912   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Predicted  \
0       2.520742  -1.544670       -1.036672         1.293353          0   
1       0.808126   0.647388        0.964625         0.926435          0   
2       0.808126  -1.544670       -1.036672         0.291500          0   
3      -0.904489   0.647388        0.964625        -0.151796          0   
4       0.808126   0.647388       -1.036672        -0.119396          0   

   Actual  
0       1  
1       0  
2       1  
3       0  
4       0

In [36]:
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.84      0.97      0.90      1990
           1       0.70      0.30      0.42       510

    accuracy                           0.83      2500
   macro avg       0.77      0.63      0.66      2500
weighted avg       0.81      0.83      0.80      2500



In [37]:
print("accuracy", metrics.accuracy_score(Y_test, Y_pred))

accuracy 0.8312


In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [39]:
print("Confusion Matrix \n")
print(cm)

Confusion Matrix 

[[1924   66]
 [ 356  154]]
